import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

const packageDirectory = resolve(import.meta.dirname, '..');

describe('generated token CSS', () => {
  it('combines scale and color tokens into the baseline', async () => {
    const baseline = await readFile(resolve(packageDirectory, 'dist/baseline.css'), 'utf8');

    expect(baseline).toContain('Generated by Sass from scale.css and color.css. Do not edit.');
    expect(baseline).toContain('--btn-py: calc(11 * var(--u));');
    expect(baseline).toContain('--ctrl-h: calc(42 * var(--u));');
    expect(baseline).toContain('--input-py: calc(13 * var(--u));');
    expect(baseline).toContain('--success: #039855;');
    expect(baseline).toContain('--warning: #dc6803;');
    expect(baseline).toContain('--accent-000: #fff;');
    expect(baseline).toContain('--accent-309: color-mix(in srgb, var(--accent) 90%, #242424);');
    expect(baseline).toContain('.theme-dark');
    expect(baseline).toContain('.theme-density-s');
    expect(baseline).toContain('.theme-light.theme-high-contrast');
    expect(baseline).toContain('.theme-dark.theme-color-deficiency');
  });

  it('contains density-scaled geometry tokens', async () => {
    const scale = await readFile(resolve(packageDirectory, 'dist/scale.css'), 'utf8');

    expect(scale).toContain('--sf: 1;');
    expect(scale).toContain('--u: calc(1px * var(--sf));');
    expect(scale).toContain('--sp-6: calc(24 * var(--u));');
    expect(scale).toContain('--input-py: calc(13 * var(--u));');
    expect(scale).toContain('--k64: calc(64 * var(--u));');
    expect(scale).toContain('.theme-density-s');
    expect(scale).toContain('--sf: 0.9;');
    expect(scale).toContain('.theme-density-m');
    expect(scale).toContain('.theme-density-l');
    expect(scale).toContain('--sf: 1.125;');
  });

  it('contains the root-scoped accent palette', async () => {
    const color = await readFile(resolve(packageDirectory, 'dist/color.css'), 'utf8');

    expect(color).toContain('--theme-accent-color: #005eb8;');
    expect(color).toContain('--theme-accent-light: #005eb8;');
    expect(color).toContain('--theme-accent-dark: #3180dc;');
    expect(color).toContain('--theme-accent-high-contrast-dark: #4997f5;');
    expect(color).toContain('.theme-light');
    expect(color).toContain('--accent: var(--theme-accent-light);');
    expect(color).toContain('--accent-hover: var(--theme-accent-light-hover);');
    expect(color).toContain('--accent-active: var(--theme-accent-light-active);');
    expect(color).toContain('--on-accent-rgb: 255, 255, 255;');
    expect(color).toContain('--focus-ring-rgb: var(--accent-rgb);');
    expect(color).toContain('--shadow-btn: 0 4px 12px -4px rgb(var(--accent-rgb) / 45%);');
    expect(color).toContain('.theme-dark');
    expect(color).toContain('--accent: var(--theme-accent-dark);');
    expect(color).toContain('--accent-hover: var(--theme-accent-dark-hover);');
    expect(color).toContain('--accent-active: var(--theme-accent-dark-active);');
    expect(color).toContain('.theme-light.theme-high-contrast');
    expect(color).toContain('--text: #000;');
    expect(color).toContain('--border: #000;');
    expect(color).toContain('--accent: var(--theme-accent-high-contrast-light);');
    expect(color).toContain('--success: #026639;');
    expect(color).toContain('--success-bg: #039855;');
    expect(color).toContain('--on-success: #000;');
    expect(color).toContain('--warning: #8f4402;');
    expect(color).toContain('--warning-bg: #dc6803;');
    expect(color).toContain('--on-warning: #000;');
    expect(color).toContain('--danger: #ab2419;');
    expect(color).toContain('--danger-bg: #da3427;');
    expect(color).toContain('--on-danger: #000;');
    expect(color).toContain('.theme-dark.theme-high-contrast');
    expect(color).toContain('--text: #fff;');
    expect(color).toContain('--border: #fff;');
    expect(color).toContain('--accent: var(--theme-accent-high-contrast-dark);');
    expect(color).toContain('.theme-light.theme-color-deficiency');
    expect(color).toContain('--success: #06c;');
    expect(color).toContain('--warning: #a94700;');
    expect(color).toContain('--danger: #6b3fa0;');
    expect(color).toContain('.theme-dark.theme-color-deficiency');
    expect(color).toContain('--success: #66b3ff;');
    expect(color).toContain('--warning: #ffb366;');
    expect(color).toContain('--danger: #d4a6ff;');
    expect(color).toContain('--success: #039855;');
    expect(color).toContain('--success-hover: #027a48;');
    expect(color).toContain('--on-success: var(--success);');
    expect(color).toContain('--on-warning: var(--warning);');
    expect(color).toContain('--on-danger: var(--danger);');
    expect(color).toContain('--success-bg: #e6f5ee;');
    expect(color).toContain('--success-4: #6ce9a6;');
    expect(color).toContain('--warning: #fdb022;');
    expect(color).toContain('--warning-bg: rgb(253 176 34 / 22%);');
    expect(color).toContain('--warning-4: #f79009;');
    expect(color).toContain('--danger: #d92d20;');
    expect(color).toContain('--danger-bg-hover: #f8d9d7;');
    expect(color).toContain('--danger-4: #f04438;');
    expect(color).toContain('--disabled-border: #4a626a;');
    expect(color).toContain('--accent-000: #fff;');
    expect(color).toContain('--accent-009: #000;');
    expect(color).toContain('--accent-000: #000;');
    expect(color).toContain('--accent-009: #fff;');
    expect(color).toContain('--accent-100: color-mix(in srgb, var(--accent) 10%, #fff);');
    expect(color).toContain('--accent-109: color-mix(in srgb, var(--accent) 100%, #2f2f2f);');
  });
});
