import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { compileStringAsync } from 'sass';

const packageDirectory = import.meta.dirname;
const sourceDirectory = resolve(packageDirectory, 'src');
const outputDirectory = resolve(packageDirectory, 'dist');
const baselinePath = resolve(outputDirectory, 'baseline.css');
const scalePath = resolve(sourceDirectory, 'scale.css');
const colorPath = resolve(sourceDirectory, 'color.css');
const patchPath = resolve(sourceDirectory, 'patch.css');

async function compileTokenCss(path) {
  const source = await readFile(path, 'utf8');
  const { css } = await compileStringAsync(source, {
    style: 'expanded',
    url: pathToFileURL(path),
  });

  return css.trim();
}

const [scale, color, patch] = await Promise.all([
  compileTokenCss(scalePath),
  compileTokenCss(colorPath),
  compileTokenCss(patchPath),
]);

await mkdir(outputDirectory, { recursive: true });
await Promise.all([
  writeFile(
    baselinePath,
    `/* Generated by Sass from scale.css and color.css. Do not edit. */\n\n${scale}\n\n${color}\n`,
    'utf8',
  ),
  writeFile(resolve(outputDirectory, 'color.css'), `${color}\n`, 'utf8'),
  writeFile(resolve(outputDirectory, 'scale.css'), `${scale}\n`, 'utf8'),
  writeFile(resolve(outputDirectory, 'patch.css'), `${patch}\n`, 'utf8'),
]);
